tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/services"

brew "asdf"
brew "coreutils"
brew "curl"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gnupg"
brew "grep"
brew "imagemagick"
brew "libffi"
brew "libiconv"
brew "librsvg"
brew "libssh2"
brew "libxslt"
brew "libyaml"
brew "neovim"
brew "openssh"
brew "openssl"
brew "readline"
brew "rename"
brew "screen"
brew "sdl2"
brew "starship"
brew "svn" # needed for fonts
brew "telnet"
brew "tree"
brew "unzip"
brew "watch"
brew "xz"
brew "zlib"
brew "zsh-completions"
brew "zsh"

cask "alfred"
cask "aptible" if ENV["BLH"]
cask "authy"
cask "brave-browser"
cask "caffeine"
cask "chromedriver"
cask "copilot"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-alfa-slab-one"
cask "font-fauna-one"
cask "font-fira-mono-nerd-font"
cask "font-merriweather"
cask "font-merriweather-sans"
cask "font-menlo-for-powerline"
cask "font-nunito"
cask "font-oswald"
cask "font-playfair-display"
cask "font-playfair-display-sc"
cask "font-poller-one"
cask "font-raleway"
cask "font-roboto"
cask "font-roboto-slab"
cask "google-chrome"
cask "hyper"
cask "imageoptim"
cask "ngrok"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "tomighty"
cask "visual-studio-code"

mas "Kelir", id: 1145215534
mas "Things", id: 904280696
mas "Xcode", id: 497799835
