# starship config docs: https://starship.rs/config

# Don't print a new line at the start of the prompt
add_newline = false

# removes noisy language-specific displays
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$custom\
$character\
$memory_usage
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_status]
stashed = ""
staged = "[+](bold green)[$count](bold green)"
